import React from 'react'
import MainLayout from '../components/MainLayout';
export const metadata = {
  title: "About",
  description: "Generated by create next app",
  icons: {
    icon: "/UrbanKicks-logo-transparent.png"
  },
};
export default function About() {
  return (
    <MainLayout>
      <div>About</div>
    </MainLayout>
  )
}
