import React from 'react'
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
  icons: {
    icon: "/UrbanKicks-logo-transparent.png"
  },
};
export default function Login() {
  return (
    <div>Login</div>
  )
}
