import React from 'react'
export const metadata = {
  title: "SignUp",
  description: "Generated by create next app",
  icons: {
    icon: "/UrbanKicks-logo-transparent.png"
  },
};
export default function SignUp() {
  return (
    <div>SignUp</div>
  )
}
