import React from 'react'
import MainLayout from '../components/MainLayout';
export const metadata = {
  title: "Products",
  description: "Generated by create next app",
  icons: {
    icon: "/UrbanKicks-logo-transparent.png"
  },
};
export default function Products() {
  return (
   <MainLayout>
     <div>Products</div>
   </MainLayout>
  )
}
